apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: springboot-custom-template
  title: Spring Boot Service
  description: Create a simple microservice using Spring Boot Java
  tags:
    - recommended
    - java
    - spring-boot
spec:
  owner: service@example.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this service does.
      path:
        title: Doc. Path
        type: string
        description: Path Doc. Open Api
      http_port:
        title: Port
        type: integer
        default: 8080
        description: The port to run the gRPC service on
