apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  tags:
    - java
  annotations:
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
  providesApis:
    - {{cookiecutter.component_id | jsonify}}

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition: |
    openapi: 3.0.1
    info:
      title: OpenAPI definition
      version: v0
    servers:
    - url: http://kong/{{cookiecutter.path}}/api-documentation
      description: Generated server url
    paths:
      /demo:
        get:
          tags:
          - demo-controller-impl
          summary: Retorna uma String com valor Hello concatenada com o valor passado
            por parâmetro no request
          operationId: hello
          parameters:
          - name: param
            in: query
            required: true
            schema:
              type: string
          responses:
            "200":
              description: Hello + valor passado por parâmetro
              content:
                '*/*':
                  schema:
                    type: string
    components: {}

