apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.component_id | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  tags:
    - java
  annotations:
    github.com/project-slug: {{cookiecutter.destination.git.owner + "/" + cookiecutter.destination.git.name}}
    backstage.io/techdocs-ref: url:{{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "test-springboot-backstage-api"
  description: springboot test app
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition: 
    $text: http://kong/{{cookiecutter.path}}/v3/api-docs

